/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorIdRouteImport } from './routes/doctor.$id'
import { Route as DashboardPatientIndexRouteImport } from './routes/dashboard.patient.index'
import { Route as DashboardDoctorIndexRouteImport } from './routes/dashboard.doctor.index'
import { Route as DashboardAssistantIndexRouteImport } from './routes/dashboard.assistant.index'
import { Route as DashboardPatientPrescriptionsRouteImport } from './routes/dashboard.patient.prescriptions'
import { Route as DashboardPatientHistoryRouteImport } from './routes/dashboard.patient.history'
import { Route as DashboardPatientAppointmentsRouteImport } from './routes/dashboard.patient.appointments'
import { Route as DashboardDoctorScheduleRouteImport } from './routes/dashboard.doctor.schedule'
import { Route as DashboardDoctorAssistantsRouteImport } from './routes/dashboard.doctor.assistants'

const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIdRoute = DoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientIndexRoute = DashboardPatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorIndexRoute = DashboardDoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantIndexRoute = DashboardAssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientPrescriptionsRoute =
  DashboardPatientPrescriptionsRouteImport.update({
    id: '/patient/prescriptions',
    path: '/patient/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientHistoryRoute = DashboardPatientHistoryRouteImport.update({
  id: '/patient/history',
  path: '/patient/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientAppointmentsRoute =
  DashboardPatientAppointmentsRouteImport.update({
    id: '/patient/appointments',
    path: '/patient/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorScheduleRoute = DashboardDoctorScheduleRouteImport.update({
  id: '/doctor/schedule',
  path: '/doctor/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorAssistantsRoute =
  DashboardDoctorAssistantsRouteImport.update({
    id: '/doctor/assistants',
    path: '/doctor/assistants',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/dashboard/doctor/assistants': typeof DashboardDoctorAssistantsRoute
  '/dashboard/doctor/schedule': typeof DashboardDoctorScheduleRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/history': typeof DashboardPatientHistoryRoute
  '/dashboard/patient/prescriptions': typeof DashboardPatientPrescriptionsRoute
  '/dashboard/assistant/': typeof DashboardAssistantIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/dashboard/patient/': typeof DashboardPatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/dashboard/doctor/assistants': typeof DashboardDoctorAssistantsRoute
  '/dashboard/doctor/schedule': typeof DashboardDoctorScheduleRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/history': typeof DashboardPatientHistoryRoute
  '/dashboard/patient/prescriptions': typeof DashboardPatientPrescriptionsRoute
  '/dashboard/assistant': typeof DashboardAssistantIndexRoute
  '/dashboard/doctor': typeof DashboardDoctorIndexRoute
  '/dashboard/patient': typeof DashboardPatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/doctors': typeof DoctorsRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/dashboard/doctor/assistants': typeof DashboardDoctorAssistantsRoute
  '/dashboard/doctor/schedule': typeof DashboardDoctorScheduleRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/history': typeof DashboardPatientHistoryRoute
  '/dashboard/patient/prescriptions': typeof DashboardPatientPrescriptionsRoute
  '/dashboard/assistant/': typeof DashboardAssistantIndexRoute
  '/dashboard/doctor/': typeof DashboardDoctorIndexRoute
  '/dashboard/patient/': typeof DashboardPatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/doctor/$id'
    | '/dashboard/doctor/assistants'
    | '/dashboard/doctor/schedule'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/history'
    | '/dashboard/patient/prescriptions'
    | '/dashboard/assistant/'
    | '/dashboard/doctor/'
    | '/dashboard/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/doctor/$id'
    | '/dashboard/doctor/assistants'
    | '/dashboard/doctor/schedule'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/history'
    | '/dashboard/patient/prescriptions'
    | '/dashboard/assistant'
    | '/dashboard/doctor'
    | '/dashboard/patient'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/doctor/$id'
    | '/dashboard/doctor/assistants'
    | '/dashboard/doctor/schedule'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/history'
    | '/dashboard/patient/prescriptions'
    | '/dashboard/assistant/'
    | '/dashboard/doctor/'
    | '/dashboard/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DoctorsRoute: typeof DoctorsRoute
  DoctorIdRoute: typeof DoctorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$id': {
      id: '/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/doctor/$id'
      preLoaderRoute: typeof DoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patient/': {
      id: '/dashboard/patient/'
      path: '/patient'
      fullPath: '/dashboard/patient/'
      preLoaderRoute: typeof DashboardPatientIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/': {
      id: '/dashboard/doctor/'
      path: '/doctor'
      fullPath: '/dashboard/doctor/'
      preLoaderRoute: typeof DashboardDoctorIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant/': {
      id: '/dashboard/assistant/'
      path: '/assistant'
      fullPath: '/dashboard/assistant/'
      preLoaderRoute: typeof DashboardAssistantIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient/prescriptions': {
      id: '/dashboard/patient/prescriptions'
      path: '/patient/prescriptions'
      fullPath: '/dashboard/patient/prescriptions'
      preLoaderRoute: typeof DashboardPatientPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient/history': {
      id: '/dashboard/patient/history'
      path: '/patient/history'
      fullPath: '/dashboard/patient/history'
      preLoaderRoute: typeof DashboardPatientHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient/appointments': {
      id: '/dashboard/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/dashboard/patient/appointments'
      preLoaderRoute: typeof DashboardPatientAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/schedule': {
      id: '/dashboard/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/dashboard/doctor/schedule'
      preLoaderRoute: typeof DashboardDoctorScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/assistants': {
      id: '/dashboard/doctor/assistants'
      path: '/doctor/assistants'
      fullPath: '/dashboard/doctor/assistants'
      preLoaderRoute: typeof DashboardDoctorAssistantsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDoctorAssistantsRoute: typeof DashboardDoctorAssistantsRoute
  DashboardDoctorScheduleRoute: typeof DashboardDoctorScheduleRoute
  DashboardPatientAppointmentsRoute: typeof DashboardPatientAppointmentsRoute
  DashboardPatientHistoryRoute: typeof DashboardPatientHistoryRoute
  DashboardPatientPrescriptionsRoute: typeof DashboardPatientPrescriptionsRoute
  DashboardAssistantIndexRoute: typeof DashboardAssistantIndexRoute
  DashboardDoctorIndexRoute: typeof DashboardDoctorIndexRoute
  DashboardPatientIndexRoute: typeof DashboardPatientIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDoctorAssistantsRoute: DashboardDoctorAssistantsRoute,
  DashboardDoctorScheduleRoute: DashboardDoctorScheduleRoute,
  DashboardPatientAppointmentsRoute: DashboardPatientAppointmentsRoute,
  DashboardPatientHistoryRoute: DashboardPatientHistoryRoute,
  DashboardPatientPrescriptionsRoute: DashboardPatientPrescriptionsRoute,
  DashboardAssistantIndexRoute: DashboardAssistantIndexRoute,
  DashboardDoctorIndexRoute: DashboardDoctorIndexRoute,
  DashboardPatientIndexRoute: DashboardPatientIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DoctorsRoute: DoctorsRoute,
  DoctorIdRoute: DoctorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
